new script for local vpn_addr/modified .bashrc

diff --git a/executable-files/_vpnaddr b/executable-files/_vpnaddr
--- a/executable-files/_vpnaddr
+++ b/executable-files/_vpnaddr
@@ -1,2 +1,15 @@
 #!/bin/env bash
-ip -4 addr | grep tun0 | tail -1 | grep -o -E "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}" | tr -d '\n'
+
+vpn_ip=$(ip -4 addr | grep -i tun0 | grep -o -E "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}" | tr -d '\n')
+
+if [[ $vpn_ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]];
+then
+    uid=$(id | grep -oP '(?<=uid=)[0-9]+')
+    case $uid in
+        "0") sed -i "138s/.*/export vpn_ip=$vpn_ip/" ~/.bashrc; sed -i "138s/.*/export vpn_ip=$vpn_ip/" /home/*/.bashrc;;
+        *) sed -i "138s/.*/export vpn_ip=$vpn_ip/" ~/.bashrc;;
+    esac
+else
+    echo "Error in vpn addr"
+    exit 1
+fi
